FROM python:3.13-slim
# Instalar dependencias de Tkinter
RUN apt-get update && apt-get install -y python3-tk libx11-6 libxft2 libxrender1 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar dependencias del sistema y Pillow
RUN apt-get update && apt-get install -y libjpeg-dev zlib1g-dev && \
    pip install pillow
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "kafka_consumer_predictor.py"]
